```{r}
#| label: setup
#| include: false
library(scan)
library(scplot)
```

```{r}
#| label: scplot-basic-1
scplot(exampleAB)
```

```{r}
#| label: scplot-basic-2
#| eval: false

scplot(exampleABC) |>
  add_title("My plot") |>
  set_xlabel("Days", color = "red", size = 1.3)
```

```{r}
#| label: scplot-dataline
scplot(exampleAB_add) |>
  set_dataline("depression")
```

```{r}
scplot(exampleAB_add) |>
  set_dataline(
    line = list(colour = "darkred", linewidth = 2), 
    point = list(colour = "black", size = 3, shape = 15)
  )
```

```{r}
#| label: scplot-statline-descriptives
scplot(exampleABC) |>
  add_statline("mean") |>
  add_statline("max") |>
  add_statline("min") |> 
  add_statline("median")
```

```{r}
#| label: scplot-statline-descriptives-phases
scplot(exampleABC) |>
  add_statline("mean", phase = "A") |>
  add_statline("max", phase = c("B", "C")) |>
  add_statline("min", phase = c(2, 3)) |> 
  add_legend()
```

```{r}
#| label: scplot-statline-trend
scplot(exampleABC) |>
  add_statline("trend") |>
  add_statline("trendA")
```

```{r}
#| label: scplot-statline-trendA-methods

scplot(exampleABC) |> 
  add_statline("trendA", label = "OLS") |> 
  add_statline("trendA", method = "theil-sen", label = "Theil-Sen") |> 
  add_statline("trendA", method = "bisplit", label = "Bisplit") |> 
  add_statline("trendA", method = "trisplit", label = "Trisplit") |> 
  add_legend()

```

```{r}
#| label: scplot-statline-4
scplot(exampleABC) |>
  add_statline("loess") |>
  add_statline("moving mean")
```

```{r}
#| label: scplot-statline-5
scplot(exampleABC) |>
  add_statline("moving mean", lag = 1) |>
  add_statline("quantile", probs = 0.75)
```

```{r}
#| label: scplot-dataline-1
scplot(exampleAB_add) |>
  set_dataline("cigarrets") |>
  add_statline("mean", variable = "cigarrets") |>
  add_statline("trend")
```

```{r}
#| label: scplot-marks-1
scplot(exampleABC) |>
  add_marks(case = 1, positions = c(7, 12)) |>
  add_marks(case = 3, positions = c(3, 17), color = "blue", size = 7)
```

```{r}
#| label: scplot-marks-2
scplot(exampleABC) |>
  add_marks(case = 1, positions = "mt > 15") |>
  add_marks(case = 2, positions = 'phase == "B"', color = "green", size = 5) |>
  add_marks(case = 3, positions = "values > quantile(values, probs = 0.80)", color = "blue", size = 7) |>
  add_marks(case = "all", positions = "values < quantile(values, probs = 0.20)", color = "yellow", size = 7) |>
  add_caption("red: mt > 15 in case 1; 
green: phase 'B' in case 2; 
blue: values > 80% quantile of case 3; 
yellow: values < 20% quantile of all cases")
```

```{r}
#| label: scplot-marks-3
scplot(exampleABC_outlier) |> 
  add_marks(positions = outlier(exampleABC_outlier), size = 3)
```

```{r text1}
scplot(exampleABC) |>
  add_text("Here!", case = 2, x = 10, y = 80, color = "red")
```

```{r}
#| label: scplot-label

scplot(exampleABC) |>
  add_line(case = 1, x0 = 6, y0 = 90, x1 = 3, y1 = 63, color = "red") |> 
  add_line(case = 2, hline = 80, color = "blue") |> 
  add_line(case = 3, vline = 15, color = "darkgreen")

```

```{r}
#| label: scplot-arrow

scplot(exampleABC) |>
  add_arrow(case = 1, x0 = 6, y0 = 90, x1 = 3, y1 = 63) |>
  add_text("Problem", case = 1, x = 6, y = 94, color = "red", size = 1, hjust = 0 ) 
```

```{r line1}
scplot(exampleABC) |>
  set_dataline(color = "blue", linewidth = 1, linetype = "dotted", 
               point = list(colour = "red", size = 1, shape = 2) )

scplot(exampleABC) |>
  set_dataline(line = list(colour = "blue", linewidth = 1, linetype = "dotted"), 
               point = list(colour = "red", size = 1, shape = 2)) 

```

```{r background1}
scplot(exampleABC) |>
  set_background(fill = "grey90", color = "black", linewidth = 2)
```

```{r pannel1}
scplot(exampleABC) |>
  set_panel(fill = "tan1", color = "palevioletred", linewidth = 2)
```

```{r pannel2}
scplot(exampleABC) |>
  set_panel(fill = c("grey80", "white", "blue4"))
```

# Themes

::: panel-tabset
```{r}
#| label: scplot-themes
#| echo: false
#| results: asis

th <- c('basic', 'minimal', 'illustration', 'clarity', 'journal', 'poster', 'handout', 'sparse','midnight', 'dark', 'playful', 'atelier', 'bauhaus',  'sienna')

p <- lapply(th, function(x) {
  scplot(exampleA1B1A2B2) |>
    set_theme(x) |> 
    set_base_text(size = 10) |> 
    add_statline("trend", phase = "A1") |>
    add_statline("loess") |>
    add_title(paste0("Theme: ", x)) 
})

for (i in seq_along(th)) {
  cat(paste0("\n\n## ", th[i], "\n\n"), collapse = "")
  print(p[[i]])
}

```
:::

```{r}
#| label: scplot-combine-themes

scplot(exampleABC) |>
  set_theme("sienna", "minimal", "small", "phase_color")
```

```{r}
my_theme <- new_theme() |>
  set_panel(color = "red", linewidth = 1) |> 
  set_base_text(size = 12, color = "blue")  |>
  set_dataline(color = "darkred", linewidth = 2)


scplot(exampleABC)  |> set_theme(my_theme)
```

```{r}
#| label: scplot-base-text

scplot(exampleAB_decreasing$Peter) |>
  set_base_text(colour = "blue", family = "serif", face = "italic", size = 14)
```

```{r}
#| label: scplot-title

scplot(exampleAB_decreasing) |>
  add_title("A new plot", color = "darkblue", size = 1.3) |>
  add_caption("Note. What a nice plot!", face = "italic", color = "darkred")
```

```{r}
#| label: scplot-legend-1

scplot(exampleABC) |>
  add_statline("mean", color = "darkred") |>
  add_statline("min", phase = "B", linewidth = 0.2, color = "darkblue") |>
  add_legend()
```

```{r}
#| label: scplot-legend-2

scplot(exampleABC) |>
  add_statline("mean", color = "darkred") |>
  add_statline("min", phase = "B", linewidth = 0.2, color = "darkblue") |>
  add_legend(position = "bottom", section_labels = NULL)
```

```{r}
#| label: scplot-legend2

scplot(exampleAB_add) |>
  set_dataline(label = "Pychological Wellbeing") |>
  set_dataline(variable = "depression", color = "darkblue", label = "Depression") |>
  add_statline(stat = "mean", label = "Wellbeing mean") |>
  add_statline(stat = "mean", variable = "depression", label = "Depression mean") |>
  set_phasenames(position = "none") |>
  set_panel(fill = c("lightblue", "grey80")) |>
  add_legend(
    position = "left",
    section_labels = c("Variables", "Section"),
    title = list(color = "brown", size = 10, face = 2),
    text = list(color = "darkgreen", size = 10, face = 2),
    background = list(color = "lightgrey")
  )
```

```{r}
#| label: scplot-axis


scplot(exampleA1B1A2B2) |> 
  set_xaxis(increment_from = 0, increment = 5, 
            color = "darkred", size = 0.7, angle = -90) |>
  set_yaxis(limits = c(0, 50), size = 0.7, color = "darkred") 
```

```{r}
#| label: scplot-axis-labels

scplot(exampleA1B1A2B2) |> 
  set_ylabel("Score", color = "darkred", angle = 0) |>
  set_xlabel("Session", color = "darkred")
```

```{r casenames1}
scplot(exampleA1B1A2B2) |>
  set_casenames(c("A", "B", "C"), color = "darkblue", size = 1)
```

```{r casenames2}
scplot(exampleA1B1A2B2) |>
  set_casenames(position = "strip", 
                background = list(fill = "lightblue"))
```

```{r valuelabels1}
scplot(exampleABC) |> 
  add_labels(text = list(color = "black", size = 0.7), 
             background = list(fill = "grey98"), nudge_y = 7)

```

```{r}
#| label: valuelabels2
scplot(exampleABC) |> 
  add_labels(text = list(color = "black", size = 0.7), 
             background = list(fill = "grey98"), nudge_y = 0)

```

```{r ridge1}
scplot(exampleAB_mpd) |> 
  add_ridge("grey50")
```

```{r extend1}

options(scplot.plot.caption = NULL, scplot.plot.theme = c("basic","minimal"))

names(byHeart2011)[1:4] <- c("Lisa", "Pat", "Anna", "Lena")

p1 <- scplot(byHeart2011[1]) |> as_ggplot()
p2 <- scplot(byHeart2011[2]) |> as_ggplot()
p3 <- scplot(byHeart2011[3]) |> as_ggplot()
p4 <- scplot(byHeart2011[4]) |> as_ggplot()

library(patchwork)
p1 + p2 + p3 + p4 + plot_annotation(
  tag_levels = "a", tag_suffix =  ")",
  title = "Data from university students learning vocabulary by heart"
)

options(scplot.plot.caption = "auto", scplot.plot.theme = "default")
```

```{r}
#| label: complex1

scplot(example_A24) |> 
  add_statline("lowess", linewidth = 1.5) |>
  add_statline("loess", linewidth = 1.5) |>
  add_statline("moving mean", lag = 3, linewidth = 1.5) |>
  set_xaxis(size = 0.8, angle = 35) |>
  set_dataline(point = "none") |>
  add_legend(position = c(0.8, 0.75), background = list(color = "grey50")) |>
  set_phasenames(c("no speedlimit", "with speedlimit"), 
                 position = "left", hjust = 0, vjust = 1) |>
  set_casenames(position = "none") |>
  add_title("Effect of a speedlimit on the A24") |>
  add_caption("Moving mean calculated with lag three", face = 3, size = 1) |>
  add_ridge(color = "lightblue")

```

```{r complex2}
scplot(exampleAB_add) |>
  set_dataline("cigarrets", point = list(size = 1)) |>
  add_statline("trend", linetype = "dashed", label = "Trend of wellbeing") |>
  add_statline("mean", variable = "cigarrets", color = "darkred", label = "Mean of cigarrets") |>
  add_marks(positions = c(14,20), size = 3, variable = "cigarrets")|>
  add_marks(positions = "cigarrets > quantile(cigarrets, 0.75)", size = 3) |>
  set_xaxis(increment = 5) |>
  set_phasenames(color = NA) |>
  set_casenames(position = "strip") |>
  add_legend(
    section_labels = c("", ""),
    text = list(face = 3)
  ) |>
  set_panel(fill = c("lightblue", "grey80")) |>
  add_ridge(color = "snow", variable = "cigarrets") |>
  add_labels(variable = "cigarrets", nudge_y = 2, 
             text = list(color = "blue", size = 0.5)) |>
  add_labels(nudge_y = 2, text = list(color = "black", size = 0.5),
             background = list(fill = "white"))


```

```{r complex3}
scplot(exampleA1B1A2B2) |> 
  set_theme("basic") |>
  set_theme_element(panel.spacing.y = unit(0, "points")) |> 
  set_xaxis(increment = 4, size = 0.7) |>
  set_yaxis(color = "sienna3") |>
  set_ylabel("Points", color = "sienna3", angle = 0) |>
  set_xlabel("Weeks", size = 1, color = "brown") |>
  add_title("Points by week", color = "sienna4", face = 3) |>
  add_caption("An extensive Example.",
              color = "black", size = 1, face = 3) |>
  set_phasenames(c("Baseline", "Intervention", "Fall-Back", "Intervention_2"), 
                 size = 0) |>
  add_ridge(scales::alpha("lightblue", 0.5)) |>
  set_casenames(labels = sample_names(3), color = "steelblue4", size = 0.7) |>
  set_panel(fill = c("grey80", "grey95"), color = "sienna4") |>
  add_grid(color = "grey85", linewidth = 0.1) |>
  set_dataline(linewidth = 0.5, linetype = "solid", 
               point = list(colour = "sienna4", size = 0.5, shape = 18)) |>
  add_labels(text = list(color = "sienna", size = 0.7), nudge_y = 4) |>
  set_separator(linewidth = 0.5, linetype = "solid", color = "sienna") |>
  add_statline(stat = "trendA", color = "tomato2") |>
  add_statline(stat = "max", phase = c(1, 3), linetype = "dashed") |>
  add_marks(case = 1:2, positions = 14, color = "red3", size = 2, shape = 4) |>
  add_marks(case = "all", positions = "values < quantile(values, 0.1)", 
            color = "blue3", size = 1.5) |>
  add_marks(positions = outlier(exampleABAB), color = "brown", size = 2) |>
  add_text(case = 1, x = 5, y = 35, label = "Interesting", 
           color = "darkgreen", angle = 20, size = 0.7) |>
  add_arrow(case = 1, 5, 30, 5, 22, color = "steelblue") |>
  set_background(fill = "white") |>
  add_legend()


```

```{r complex4}
scplot(exampleAB_add) |>
  set_xaxis(expand = c(0, 0), limits = c(0, 41)) |>
  set_dataline("cigarrets", type = "bar", linewidth = 0.6, point = "none") |>
  add_statline("mean", variable = "cigarrets", color = "darkred") |>
  add_statline("trend", linetype = "dashed") |>
  set_casenames(position = "strip")
```

# new -----------

## Alternating treatment design

```{r}
scplot(scan::example_atd) |> 
  split_dataline("treatment") |> 
  add_legend()
```

```{r}
scplot(scan::example_atd) |> 
  split_dataline("treatment", labels = c("Maze", "PGC")) |> 
  add_legend()
```

## Separator

```{r}
scplot(exampleA1B1A2B2) |> 
  set_separator(linewidth = 0.5, linetype = "solid", color = "sienna")
```

```{r}
scplot(exampleA1B1A2B2) |> 
  set_separator(linewidth = 0.5, linetype = "solid", color = "sienna", staircase = TRUE)
```

```{r}
scplot(exampleA1B1A2B2) |> 
  set_theme("minimal", "staircase")
```
